In [9]:
import numpy as np
from matplotlib import pyplot as plt


@np.vectorize
def f(c):
    return (c - 32) * (5/9)

temp_f = np.array([32, 68, 100, 212, 77])
temp_c = f(temp_f)
print([f"{x:.2f}" for x in temp_c])

['0.00', '20.00', '37.78', '100.00', '25.00']


In [8]:
@np.vectorize
def to_power(x, y):
    return np.power(x, y)

numbers = np.array([2, 3, 4, 5])
powers = np.array([1, 2, 3, 4])
result = to_power(numbers, powers)
print(result)

[  2   9  64 625]


In [10]:
A = np.array([[4, 5, 6],
              [3, -1, 1],
              [2, 1, -2]])
B = np.array([7, 4, 5])

solution = np.linalg.solve(A, B)
print(solution)

[ 1.7027027   0.62162162 -0.48648649]


In [11]:
C = np.array([
    [10, -2, 3],
    [-2, 8, -1],
    [3, -1, 6]
])

D = np.array([12, -5, 15])
solution2 = np.linalg.solve(C, D)
print(np.round(solution2, 2))

[ 0.49 -0.23  2.22]


In [16]:
from PIL import Image

def flip_img_(img):
    horizontal_flip = np.fliplr(img)
    vertical_flip = np.flipud(img)
    return horizontal_flip, vertical_flip

def add_noise(img_array, noise_level=30):
    noise = np.random.randint(-noise_level, noise_level, img_array.shape, dtype=np.int16)
    noisy_image = img_array.astype(np.int16) + noise
    noisy_image = np.clip(noisy_image, 0, 255)
    return noisy_image.astype(np.uint8)

def brighten_channel(img_array, channel=0, brightness=40):
    img_bright = img_array.copy()
    img_bright[..., channel] = np.clip(img_bright[..., channel] + brightness, 0, 255)
    return img_bright

def apply_mask(img_array, mask_size=(100, 100)):
    img_masked = img_array.copy()
    h, w, _ = img_array.shape
    cx, cy = w // 2, h // 2 
    x1, y1 = cx - mask_size[0] // 2, cy - mask_size[1] // 2
    x2, y2 = x1 + mask_size[0], y1 + mask_size[1]
    img_masked[y1:y2, x1:x2] = (0, 0, 0) 
    return img_masked

location = 'images/birds.jpg'
img = Image.open(location)
img_array = np.array(img)

horizontal_flip, vertical_flip = flip_img_(img)

img_with_noise_array = add_noise(img_array, 40)

bright_red = brighten_channel(img_array, channel=0, brightness=40)

masked_image = apply_mask(img_array)

Image.fromarray(horizontal_flip).save("images/horizontal_flip.jpg")
Image.fromarray(vertical_flip).save("images/vertical_flip.jpg")
Image.fromarray(img_with_noise_array).save("images/noisy_image.jpg")
Image.fromarray(bright_red).save("images/bright_red.jpg")
Image.fromarray(masked_image).save("images/masked_image.jpg")

Image.fromarray(horizontal_flip).show()
Image.fromarray(vertical_flip).show()
Image.fromarray(img_with_noise_array).show()
Image.fromarray(bright_red).show()
Image.fromarray(masked_image).show()