In [39]:
import numpy as np



In [40]:
vector = np.arange(10, 50)



In [41]:
matrix_3x3 = np.arange(9).reshape(3, 3)

In [42]:
arr3 = np.eye(3, dtype=int)


In [43]:
arr4 = np.random.rand(3, 3, 3)


In [44]:
arr5 = np.random.randint(0, 100, size=(10, 10))

print(f"MIN: {np.min(arr5)}")
print(f"MAX: {np.max(arr5)}")

MIN: 1
MAX: 96


In [45]:
arr7 = np.random.randint(0, 100, size=(5, 5))
min = np.min(arr7)
max = np.max(arr7)
norm = (arr7 - min) / (max - min)
print(f"Normalized: {norm}")


Normalized: [[0.13186813 0.         1.         0.71428571 0.92307692]
 [0.83516484 0.36263736 0.1978022  0.49450549 0.        ]
 [0.95604396 0.68131868 0.75824176 0.37362637 0.87912088]
 [0.1978022  0.8021978  0.89010989 0.02197802 0.25274725]
 [0.46153846 0.25274725 0.01098901 0.91208791 0.84615385]]


In [46]:
arr6 = np.random.randint(0, 1000, size=30)
print(f"Mean: {np.mean(arr6)}")

Mean: 492.3333333333333


In [47]:
a8 = np.random.randint(0, 100, size=(5, 3))
b8 = np.random.randint(0, 100, size=(3, 2))

print(f"Product: {np.dot(a8, b8)}")

Product: [[ 5720  7774]
 [10212 15936]
 [10966 16112]
 [ 4540  6860]
 [ 6522 10476]]


In [48]:
a9 = np.random.randint(0, 100, size=(3, 3))
b9 = np.random.randint(0, 100, size=(3, 3))
print(f"Product: {np.dot(a9, b9)}")

Product: [[10588  2503  2283]
 [ 4160   150   142]
 [ 5484  4156  4048]]


In [49]:
arr10 = np.random.randint(0, 10, size=(4, 4))
print(f"Transposed: {np.transpose(arr10)}")

Transposed: [[1 4 6 2]
 [4 0 6 1]
 [9 6 7 1]
 [5 6 0 3]]


In [50]:
arr11 = np.random.randint(0, 10, size=(3, 3))
print(f"Determinant: {np.linalg.det(arr11)}")

Determinant: 161.99999999999994


In [51]:
a12 = np.random.randint(0, 100, size=(3, 4))
b12 = np.random.randint(0, 100, size=(4, 3))


In [52]:
a13 = np.random.randint(0, 100, size=(3, 3))
b13 = np.random.randint(0, 100, size=(3, 1))

In [53]:
print(f"Solution: {np.linalg.solve(a13, b13)}")

Solution: [[-0.91277225]
 [ 1.44802586]
 [ 1.83172291]]


In [54]:
arr15 = np.random.randint(0, 100, size=(5, 5))

print(f"Row sum: {np.sum(arr15, axis=1)}")
print(f"Column sum: {np.sum(arr15, axis=0)}")

Row sum: [210 384 277 131 193]
Column sum: [233 104 195 338 325]
